### ISSUE TITLE
Firmware Missing neopixel and adafruit_register Libraries

### ISSUE THREAD

**Issue by TheSilentDefender** [proveskit/flight_software#6]
### Expected Behavior
All required libraries should be pre-installed in the firmware.

### Current Behavior
The board complains about missing the `neopixel` library and the `adafruit_register` library. Attempting to add these libraries manually results in further issues.

### Steps to Reproduce
1. Start with a clean flash of the firmware.
2. Copy files from the FC board folder.
3. Attempt to run the software.

### Detailed Description
When attempting to run the software on freshly flashed firmware from the flight_controller_board, the board fails due to missing dependencies. Specifically, it complains that the `neopixel` and `adafruit_register` libraries are not found, which prevents the application from running correctly.

Manually adding the `neopixel` library from the 9.x bundle provided by Adafruit resolves the `neopixel` issue, but the board complains about the missing `adafruit_register` library.
```
Traceback (most recent call last):
  File "code.py", line 12, in <module>
  File "main.py", line 6, in <module>
  File "/lib/pysquared.py", line 20, in <module>
  File "/lib/adafruit_pca9685.py", line 39, in <module>
ImportError: no module named 'adafruit_register'
```
Attempts to manually add the `adafruit_register` library from the 8.x and 9.x bundles result in compatibility errors.
```
code.py output:
incompatible .mpy file
Traceback (most recent call last):
  File "code.py", line 12, in <module>
  File "main.py", line 6, in <module>
  File "/lib/pysquared.py", line 21, in <module>
ValueError: incompatible .mpy file
```

**Comment by Mikefly123** [comment]
Hey @TheSilentDefender! Thanks for bringing this up. It turns out that the firmware changed between the last version and this version so a bunch of the pin definitions broke. I went ahead and fixed most of them (notable exception being the reset logic). It should work now! 

Try the code that is in is currently on in Commit # 473aca5
