### ISSUE TITLE
Implement new IMU Code

### ISSUE THREAD

**Issue by Mikefly123** [proveskit/flight_software#9]
There is a new IMU on the Internal FC Board V1a. We need to add the libraries and initializations.

**Comment by Mikefly123** [comment]
In order to make this work, you will need to pull in the following libraries from the Adafruit side: 
https://github.com/adafruit/Adafruit_LSM6DS
https://github.com/adafruit/Adafruit_LSM303_Accel

**Comment by Mikefly123** [comment]
# Electrical Hookup for the IMU Components
<img width="1397" alt="Screenshot 2024-06-27 at 9 25 53 PM" src="https://github.com/proveskit/flight_software/assets/61564344/cc397f1a-afcf-4973-af30-334e182b0c27">

**Comment by Sankie005** [comment]
Tried giving it a shot, I don't have access to a board or a test platform right now so the results are going to be mixed, however I hope that some parts of the code can be reused, I've Dm'd you the code and explanation instead of creating a new branch
